#!/usr/bin/env bash
# Start from the repository root.
cd ./$(git rev-parse --show-cdup)

# Delete .pyc files and empty directories.
find . -name "*.pyc" -delete
find . -name "*.pyo" -delete
find . -name "*.class" -delete
find . -type d -empty -delete

# delete classpath-files for java-projects
rm -f .syntastic_classpath

# update ctags for project
ctags -R 2> /dev/null > /dev/null

# clear ctrlp-cache (currently all caches)
rm -f ~/.cache/ctrlp/*.txt

# check virtualenv-requirements
if [ -n $VIRTUAL_ENV ]; then
    if [ -a ./requirements.txt ]; then
        echo "checking requirements.txt"
        pip install -q -r ./requirements.txt
    fi

    if [ -a ./requirements_dev.txt ]; then
        echo "checking requirements_dev.txt"
        pip install -q -r ./requirements_dev.txt
    fi
fi
