#!/usr/bin/env bash
# Start from the repository root.
cd "$(git rev-parse --show-toplevel 2>/dev/null)" || exit 1

# Delete .pyc files and empty directories.
# find . -name "*.py?" -delete
# find . -type d -empty -delete

# update ctags for project
nohup git ls-files . --cached --exclude-standard --others | ctags -L - 2> /dev/null > /dev/null &
