#!/usr/bin/env bash
# Start from the repository root.
cd ./$(git rev-parse --show-cdup)

# Delete .pyc files and empty directories.
# find . -name "*.py?" -delete
# find . -type d -empty -delete

# update ctags for project
# git ls-files . --cached --exclude-standard --others | ctags -L - 2> /dev/null > /dev/null
