env:
  TERM: xterm-256color

shell:
  program: /usr/local/bin/fish
  args:
    - -l
    - -c
    - tmux attach || tmux new

window:
  # startup_mode: Fullscreen
  dynamic_title: true

scrolling:
  history: 0  # disable history, since it's in tmux

font:
  normal:
    family: 'BlexMono NF'
    style: Light

  bold:
    family: 'BlexMono NF'
    style: Medium

  italic:
    family: 'BlexMono NF'
    style: LightItalic

  bold_italic:
    family: 'BlexMono NF'
    style: MediumItalic

  # Point size
  size: 15.0
  offset:
    x: 0
    y: 0

  use_thin_strokes: true

draw_bold_text_with_bright_colors: false

debug:
  render_timer: false
  persistent_logging: false  # tmux does it

# github Alacritty Colors
colors:
  # Default colors
  primary:
    background: '0xffffff'
    foreground: '0x586069'

  # Normal colors
  normal:
    black:   '0x697179'
    red:     '0xd03d3d'
    green:   '0x14ce14'
    yellow:  '0x949800'
    blue:    '0x0451a5'
    magenta: '0xbc05bc'
    cyan:    '0x0598bc'
    white:   '0x586069'

  # Bright colors
  bright:
    black:   '0x666666'
    red:     '0xcd3131'
    green:   '0x14ce14'
    yellow:  '0xb5ba00'
    blue:    '0x0451a5'
    magenta: '0xbc05bc'
    cyan:    '0x0598bc'
    white:   '0x586069'

  indexed_colors:
    - { index: 16, color: '0xd18616' }
    - { index: 17, color: '0xcd3131' }

selection:
  semantic_escape_chars: ",│`|:\"' ()[]{}<>\t"
  save_to_clipboard: false

cursor:
  style: Block
  unfocused_hollow: true

live_config_reload: true

alt_send_esc: true

mouse:
  hide_when_typing: true

  # url:
  #   launcher:
  #     program: open

key_bindings:
  - { key: Key0,   mods: Command,         action: ResetFontSize    }
  - { key: Equals, mods: Command,         action: IncreaseFontSize }
  - { key: Plus,  mods: Command,         action: IncreaseFontSize }
  - { key: Minus,  mods: Command,         action: DecreaseFontSize }
  - { key: K,      mods: Command,         action: ClearHistory     }
  - { key: K,      mods: Command,         chars: "\x0c"            }
  - { key: V,      mods: Command,         action: Paste            }
  - { key: C,      mods: Command,         action: Copy             }
  - { key: H,      mods: Command,         action: Hide             }
  - { key: Q,      mods: Command,         action: Quit             }
  - { key: F,      mods: Command|Control, action: ToggleFullscreen }

# simulate old iterm tab/split commands with tmux (the ones I used)
  - { key: W,      mods: Command,         chars: "\x01\x26"      } # close window
  - { key: T,      mods: Command,         chars: "\x01\x63"      } # new window
  - { key: N,      mods: Command,         chars: "\x01\x6e"      } # next window
  - { key: P,      mods: Command,         chars: "\x01\x70"      } # previous window
  - { key: D,      mods: Command,         chars: "\x01\x7c"      } # split window horizontal
  - { key: D,      mods: Command|Shift,   chars: "\x01\x2d"      } # split window vertical
  - { key: Return, mods: Command|Shift,   chars: "\x01\x7a"      } # zoom window

# switch windows with cmd+number
  - { key: Key1,   mods: Command,         chars: "\x01\x30" }
  - { key: Key2,   mods: Command,         chars: "\x01\x31" }
  - { key: Key3,   mods: Command,         chars: "\x01\x32" }
  - { key: Key4,   mods: Command,         chars: "\x01\x33" }
  - { key: Key5,   mods: Command,         chars: "\x01\x34" }
  - { key: Key6,   mods: Command,         chars: "\x01\x35" }
  - { key: Key7,   mods: Command,         chars: "\x01\x36" }
  - { key: Key8,   mods: Command,         chars: "\x01\x37" }
  - { key: Key9,   mods: Command,         chars: "\x01\x38" }

  - { key: Paste,                    action: Paste                            }
  - { key: Copy,                     action: Copy                             }
  - { key: L,         mods: Control, action: ClearLogNotice                   }
  - { key: L,         mods: Control, chars: "\x0c"                            }
  - { key: PageUp,    mods: Shift,   action: ScrollPageUp,   mode: ~Alt       }
  - { key: PageDown,  mods: Shift,   action: ScrollPageDown, mode: ~Alt       }
  - { key: Home,      mods: Shift,   action: ScrollToTop,    mode: ~Alt       }

  - { key: End,       mods: Shift,   action: ScrollToBottom, mode: ~Alt       }


# for vim to work
  - { key: B,        mods: Alt,     chars: "\x1b[1;3D"                   }
  - { key: F,        mods: Alt,     chars: "\x1b[1;3C"                   }
  - { key: Key6,     mods: Control, chars: "\x1e"                        }

# Fix Alt as Meta in macOS
  - { key: A,         mods: Alt,       chars: "\x1ba"                       }
  - { key: B,         mods: Alt,       chars: "\x1bb"                       }
  - { key: C,         mods: Alt,       chars: "\x1bc"                       }
  - { key: D,         mods: Alt,       chars: "\x1bd"                       }
  - { key: E,         mods: Alt,       chars: "\x1be"                       }
  - { key: F,         mods: Alt,       chars: "\x1bf"                       }
  - { key: G,         mods: Alt,       chars: "\x1bg"                       }
  - { key: H,         mods: Alt,       chars: "\x1bh"                       }
  - { key: I,         mods: Alt,       chars: "\x1bi"                       }
  - { key: J,         mods: Alt,       chars: "\x1bj"                       }
  - { key: K,         mods: Alt,       chars: "\x1bk"                       }
  - { key: L,         mods: Alt,       chars: "\x1bl"                       }
  - { key: M,         mods: Alt,       chars: "\x1bm"                       }
  - { key: N,         mods: Alt,       chars: "\x1bn"                       }
  - { key: O,         mods: Alt,       chars: "\x1bo"                       }
  - { key: P,         mods: Alt,       chars: "\x1bp"                       }
  - { key: Q,         mods: Alt,       chars: "\x1bq"                       }
  - { key: R,         mods: Alt,       chars: "\x1br"                       }
  - { key: S,         mods: Alt,       chars: "\x1bs"                       }
  - { key: T,         mods: Alt,       chars: "\x1bt"                       }
  - { key: U,         mods: Alt,       chars: "\x1bu"                       }
  - { key: V,         mods: Alt,       chars: "\x1bv"                       }
  - { key: W,         mods: Alt,       chars: "\x1bw"                       }
  - { key: X,         mods: Alt,       chars: "\x1bx"                       }
  - { key: Y,         mods: Alt,       chars: "\x1by"                       }
  - { key: Z,         mods: Alt,       chars: "\x1bz"                       }
  - { key: A,         mods: Alt|Shift, chars: "\x1bA"                       }
  - { key: B,         mods: Alt|Shift, chars: "\x1bB"                       }
  - { key: C,         mods: Alt|Shift, chars: "\x1bC"                       }
  - { key: D,         mods: Alt|Shift, chars: "\x1bD"                       }
  - { key: E,         mods: Alt|Shift, chars: "\x1bE"                       }
  - { key: F,         mods: Alt|Shift, chars: "\x1bF"                       }
  - { key: G,         mods: Alt|Shift, chars: "\x1bG"                       }
  - { key: H,         mods: Alt|Shift, chars: "\x1bH"                       }
  - { key: I,         mods: Alt|Shift, chars: "\x1bI"                       }
  - { key: J,         mods: Alt|Shift, chars: "\x1bJ"                       }
  - { key: K,         mods: Alt|Shift, chars: "\x1bK"                       }
  - { key: L,         mods: Alt|Shift, chars: "\x1bL"                       }
  - { key: M,         mods: Alt|Shift, chars: "\x1bM"                       }
  - { key: N,         mods: Alt|Shift, chars: "\x1bN"                       }
  - { key: O,         mods: Alt|Shift, chars: "\x1bO"                       }
  - { key: P,         mods: Alt|Shift, chars: "\x1bP"                       }
  - { key: Q,         mods: Alt|Shift, chars: "\x1bQ"                       }
  - { key: R,         mods: Alt|Shift, chars: "\x1bR"                       }
  - { key: S,         mods: Alt|Shift, chars: "\x1bS"                       }
  - { key: T,         mods: Alt|Shift, chars: "\x1bT"                       }
  - { key: U,         mods: Alt|Shift, chars: "\x1bU"                       }
  - { key: V,         mods: Alt|Shift, chars: "\x1bV"                       }
  - { key: W,         mods: Alt|Shift, chars: "\x1bW"                       }
  - { key: X,         mods: Alt|Shift, chars: "\x1bX"                       }
  - { key: Y,         mods: Alt|Shift, chars: "\x1bY"                       }
  - { key: Z,         mods: Alt|Shift, chars: "\x1bZ"                       }
  - { key: Key1,      mods: Alt,       chars: "\x1b1"                       }
  - { key: Key2,      mods: Alt,       chars: "\x1b2"                       }
  - { key: Key3,      mods: Alt,       chars: "\x1b3"                       }
  - { key: Key4,      mods: Alt,       chars: "\x1b4"                       }
  - { key: Key5,      mods: Alt,       chars: "\x1b5"                       }
  - { key: Key6,      mods: Alt,       chars: "\x1b6"                       }
  - { key: Key7,      mods: Alt,       chars: "\x1b7"                       }
  - { key: Key8,      mods: Alt,       chars: "\x1b8"                       }
  - { key: Key9,      mods: Alt,       chars: "\x1b9"                       }
  - { key: Key0,      mods: Alt,       chars: "\x1b0"                       }
  - { key: Space,     mods: Control,   chars: "\x00"                        } # Ctrl + Space
  - { key: Grave,     mods: Alt,       chars: "\x1b`"                       } # Alt + `
  - { key: Grave,     mods: Alt|Shift, chars: "\x1b~"                       } # Alt + ~
  - { key: Period,    mods: Alt,       chars: "\x1b."                       } # Alt + .
  - { key: Key8,      mods: Alt|Shift, chars: "\x1b*"                       } # Alt + *
  - { key: Key3,      mods: Alt|Shift, chars: "\x1b#"                       } # Alt + #
  - { key: Period,    mods: Alt|Shift, chars: "\x1b>"                       } # Alt + >
  - { key: Comma,     mods: Alt|Shift, chars: "\x1b<"                       } # Alt + <
  - { key: Minus,     mods: Alt|Shift, chars: "\x1b_"                       } # Alt + _
  - { key: Key5,      mods: Alt|Shift, chars: "\x1b%"                       } # Alt + %
  - { key: Key6,      mods: Alt|Shift, chars: "\x1b^"                       } # Alt + ^
  - { key: Backslash, mods: Alt,       chars: "\x1b\\"                      } # Alt + \
  - { key: Backslash, mods: Alt|Shift, chars: "\x1b|"                       } # Alt + |
